# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faucets', '0002_auto_20180120_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSpawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('spawned', 'Spawned'), ('captured', 'Captured')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=20, max_digits=40)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_coin_spawns', to=settings.AUTH_USER_MODEL)),
                ('faucet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawns', to='faucets.Faucet')),
            ],
        ),
    ]
