# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucets', '0003_coinspawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinspawn',
            name='health',
            field=models.IntegerField(default=1),
        ),
    ]
